# Generated by Django 6.0.2 on 2026-03-16 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyCapacity',
            fields=[
                ('daily_capacity_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('daily_limit_hours', models.DecimalField(decimal_places=2, default=6, max_digits=4)),
            ],
            options={
                'db_table': 'daily_capacity',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid_user', models.UUIDField(unique=True)),
                ('name', models.TextField()),
                ('last_name', models.TextField()),
                ('streak_current', models.IntegerField(default=0)),
                ('streak_last_day', models.DateField(blank=True, null=True)),
                ('streak_best', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
    ]
