# Generated by Django 6.0.2 on 2026-02-24 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='subtask',
            constraint=models.CheckConstraint(check=models.Q(('estimated_hours__gt', 0)), name='check_estimated_hours_positive'),
        ),
    ]
