# Generated by Django 6.0.2 on 2026-02-25 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_subtask_check_estimated_hours_positive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='course',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
