# Generated by Django 6.0.2 on 2026-02-25 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_alter_activity_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='due_date',
            field=models.DateField(default='2026-01-01'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='activity',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('done', 'Hecha'), ('postponed', 'Pospuesta'), ('overdue', 'Vencida')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='activity',
            name='type',
            field=models.CharField(choices=[('exam', 'Examen'), ('quiz', 'Quiz'), ('project', 'Proyecto'), ('homework', 'Tarea'), ('presentation', 'Presentacion')], max_length=100),
        ),
    ]
