# Generated by Django 6.0.2 on 2026-02-25 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0004_alter_activity_due_date_alter_activity_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('done', 'Completada'), ('postponed', 'Postergada'), ('overdue', 'Vencida')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='activity',
            name='type',
            field=models.CharField(choices=[('exam', 'Examen'), ('quiz', 'Quiz'), ('project', 'Proyecto'), ('homework', 'Tarea'), ('presentation', 'Presentación')], max_length=100),
        ),
    ]
