# Generated by Django 6.0.2 on 2026-02-27 01:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0005_alter_activity_status_alter_activity_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ['-due_date']},
        ),
        migrations.AlterModelOptions(
            name='subtask',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='subtask',
            name='check_estimated_hours_positive',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='activity',
            name='id',
            field=models.BigAutoField(db_column='activity_id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='activity',
            name='user_id',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subtask',
            name='activity',
            field=models.ForeignKey(db_column='activity_id', on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='activities.activity'),
        ),
        migrations.AlterField(
            model_name='subtask',
            name='estimated_hours',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subtask',
            name='id',
            field=models.UUIDField(db_column='subtask_id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='subtask',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
        migrations.AlterModelTable(
            name='activity',
            table='activity',
        ),
        migrations.AlterModelTable(
            name='subtask',
            table='subtask',
        ),
        migrations.RemoveField(
            model_name='subtask',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='subtask',
            name='updated_at',
        ),
    ]
