# Generated by Django 5.0.6 on 2026-02-28 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0006_fix_subtask_to_match_supabase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtask',
            name='id',
            field=models.BigAutoField(db_column='subtask_id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='subtask',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('done', 'Done')], default='pending', max_length=20),
        ),
    ]
