# Generated by Django 5.0.6 on 2026-02-28 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0007_alter_subtask_id_alter_subtask_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtask',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('done', 'Completada'), ('postponed', 'Postergada'), ('overdue', 'Vencida')], default='pending', max_length=20),
        ),
    ]
