# Generated by Django 6.0.2 on 2026-03-16 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0008_alter_subtask_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtask',
            name='note',
            field=models.TextField(blank=True, default='', help_text='Nota opcional al posponer o cambiar estado', null=True),
        ),
    ]
