# Generated by Django 6.0.2 on 2026-03-16 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0009_subtask_note_alter_subtask_id'),
    ]

    operations = [
    ]
