# Generated by Django 6.0.2 on 2026-03-16 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0010_alter_subtask_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtask',
            name='done_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
