# Generated by Django 6.0.2 on 2026-03-17 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0011_subtask_done_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtask',
            name='id',
            field=models.BigAutoField(db_column='subtask_id', primary_key=True, serialize=False),
        ),
    ]
